version: '3.8'
services:
  database:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: employmentapp_pass
      POSTGRES_USER: employmentapp
      POSTGRES_DB: employmentapp