# Generated by Django 3.1.7 on 2021-02-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0004_auto_20210226_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permission_type',
            field=models.SmallIntegerField(choices=[(1, 'ADMIN'), (2, 'HR'), (3, 'MANAGER'), (4, 'LEADER'), (5, 'USER')], default=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.employee')),
            ],
        ),
    ]
