# Generated by Django 3.1.7 on 2021-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20210226_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.SmallIntegerField(choices=[(1, 'HOLIDAY'), (2, 'VACATION'), (3, 'MATERNITY_LEAVE')], default=1),
            preserve_default=False,
        ),
    ]
