# Generated by Django 3.1.7 on 2021-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.SmallIntegerField(choices=[(1, 'NONE'), (2, 'HOLIDAY'), (3, 'VACATION'), (4, 'MATERNITY_LEAVE')]),
        ),
    ]
