# Generated by Django 3.1.7 on 2021-03-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_employee_holiday_days_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='schedules.employee'),
        ),
    ]
